name: helm
on:
  workflow_dispatch:
  push:
    branches:
      - 'master'
  pull_request:
    branches:
      - 'master'
jobs:
  helm:
    runs-on: ubuntu-latest
    steps:
      - name: Configure helm
        run: echo "myconfig" > .helm
      - name: Helm lint
        run: echo helm lint ${{fromJSON(needs.get-version.outputs.NEXT_VERSION)}}
      - name: helm package
        run: echo helm package blabla
      - name: helm test
        run: echo helm upgrade --install test package-version-1.0.0.tgz --namespace dry-run --dry-run -f values_test.yml
      - name: helm push
        run: echo helm push package-version-1.0.0.tgz
