name: docker-helm
on:
  workflow_dispatch:
  push:
    branches:
      - 'master'
  pull_request:
    branches:
      - 'master'
jobs:
  get-version:
    runs-on: ubutun-latest
    outputs:
      CURRENT_VERSION: ${{ steps.get-version.outputs.CURRENT_VERSION }}
      NEXT_VERSION: ${{ steps.get-version.outputs.NEXT_VERSION }}
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Get-Version
        uses: Vr00mm/github-action-semver@v0.9.2
        id: get-version
  helm:
    runs-on: ubuntu-latest
    steps:
      - name: Configure helm
        run: echo "myconfig" > .helm
      - name: Helm lint
        run: echo helm lint ${{fromJSON(needs.get-version.outputs.NEXT_VERSION)}}
      - name: helm package
        run: echo helm package blabla
      - name: helm test
        run: echo helm upgrade --install test package-version-1.0.0.tgz --namespace dry-run --dry-run -f values_test.yml
      - name: helm push
        run: echo helm push package-version-1.0.0.tgz
