name: docker-build-and-push

on:
  workflow_dispatch:
  push:
    branches:
      - 'master'
  pull_request:
    branches:
      - 'master'
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Get-Version
        uses: Vr00mm/github-action-semver@v0.9.0
        id: get-version

      - name: Curren-Version
        run: echo "The current version is ${{ steps.get-version.outputs.CURRENT_VERSION }}"
      - name: Next-Version
        run: echo "The next version will be ${{ steps.get-version.outputs.NEXT_VERSION }}"

